version: '3.1'

services:
  md-users:
    build:
      context: ../microdiamond-server-users
      dockerfile: src/main/docker/Dockerfile.native
      #dockerfile: src/main/docker/Dockerfile.jvm
    restart: always
    depends_on:
      - md-db
      - md-api-gateway
    networks:
      - microdiamond

  md-auth:
    build:
      context: ../microdiamond-server-auth
      dockerfile: src/main/docker/Dockerfile.native
      #dockerfile: src/main/docker/Dockerfile.jvm
    restart: always
    depends_on:
      - md-api-gateway
    networks:
      - microdiamond

  md-db:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: postgres
    restart: always
    networks:
      - microdiamond
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: justapassword

  md-api-gateway:
    image: bitnami/kong:latest
    ports:
      - 80:8000
    environment:
      - KONG_MIGRATE=yes
      - KONG_PG_HOST=md-db
      - KONG_PG_USER=postgres
      - KONG_PG_PASSWORD=justapassword
    restart: always
    depends_on:
      - md-db
    restart: always
    networks:
      - microdiamond

networks:
  microdiamond:
    driver: bridge