version: '3.1'

services:
  md-users:
    build:
      context: ../microdiamond-server-users
      #dockerfile: src/main/docker/Dockerfile.native
      dockerfile: src/main/docker/Dockerfile.jvm
    restart: always
    depends_on:
      - md-db
      - md-api-gateway
    networks:
      - microdiamond

  md-auth:
    build:
      context: ../microdiamond-server-auth
      #dockerfile: src/main/docker/Dockerfile.native
      dockerfile: src/main/docker/Dockerfile.jvm
    restart: always
    depends_on:
      - md-api-gateway
    networks:
      - microdiamond

  md-db:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: postgres
    restart: always
    networks:
      - microdiamond
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example

  md-api-gateway:
    build:
      context: ./kong
      dockerfile: Dockerfile
    networks:
      - microdiamond
    ports:
      - "80:8000/tcp"
      - "8001:8001/tcp"
    restart: always

networks:
  microdiamond:
    driver: bridge